package locators;

public class CobranzasLocators {
    public static final String TITLE_GENERIC_XPATH = "//h3[text()='%s']";
    public static final String STEP_GENERIC_XPATH = "//*[text()='%s']/ancestor::div/div[contains(@class,'item-icon')]";
    public static final String SPINNER_XPATH = "//div[contains(@class,'ant-spin-spinning')]";
    public static final String PRELIQUIDACION_NUMERO_XPATH = "//strong[contains(normalize-space(),'Preliquidación Nro.')]";
    public static final String LISTADO_POLIZAS_TITULO_XPATH = "//h3[normalize-space()='Listado de Pólizas']";
    public static final String FILTRO_RAMA_SELECT_XPATH = "//input[@id='rama']/ancestor::div[contains(@class,'ant-select')][1]";
    public static final String FILTRO_ASEGURADO_INPUT_XPATH = "//input[@id='asegurado']";
    public static final String FILTRO_POLIZA_INPUT_XPATH = "//input[@id='poliza']";
    public static final String SELECT_OPTION_XPATH = "//div[contains(@class,'ant-select-item-option-content') and normalize-space()='%s']";
    public static final String PRELIQUIDACION_TABLA_POLIZAS_XPATH = "//h3[normalize-space()='Listado de Pólizas']/following::table[1]";
    public static final String RESUMEN_TITULO_XPATH = "//h3[normalize-space()='Resumen']";
    public static final String PRIMER_CHECKBOX_CUOTA_HABILITADO_XPATH = "(//h3[contains(normalize-space(),'Listado de P')]/following::tbody[1]//tr[contains(@class,'ant-table-row')][1]//input[@type='checkbox' and not(@disabled)])[1]";
    public static final String CONTINUAR_BUTTON_XPATH = "//button[.//span[normalize-space()='Continuar']]";
    public static final String CUOTAS_SELECCIONADAS_TITULO_XPATH = "//h3[text()='Cuotas Seleccionadas']";
    public static final String CUOTAS_SELECCIONADAS_RAMA_HEADER_XPATH = "//th[normalize-space()='Rama']";
    public static final String CUOTAS_SELECCIONADAS_POLIZA_HEADER_XPATH = "//th[contains(normalize-space(),'P')]";
    public static final String CUOTAS_SELECCIONADAS_ENDOSO_HEADER_XPATH = "//th[normalize-space()='Endoso']";
    public static final String CUOTAS_SELECCIONADAS_CUOTA_HEADER_XPATH = "//th[normalize-space()='Cuota']";
    public static final String CUOTAS_SELECCIONADAS_SUBCUOTA_HEADER_XPATH = "//th[normalize-space()='Subcuota']";
    public static final String CUOTAS_SELECCIONADAS_VENCIMIENTO_HEADER_XPATH = "//th[normalize-space()='Vencimiento']";
    public static final String CUOTAS_SELECCIONADAS_ASEGURADO_HEADER_XPATH = "//th[normalize-space()='Asegurado']";
    public static final String CUOTAS_SELECCIONADAS_SUBTOTAL_PREMIO_HEADER_XPATH = "//th[normalize-space()='Subtotal premio']";
    public static final String PRIMERA_RAMA_CUOTA_SELECCIONADA_XPATH = "(//h3[normalize-space()='Cuotas Seleccionadas']/following::tbody[1]//tr[contains(@class,'ant-table-row')][1]/td[1])[1]";
    public static final String TOTAL_PREMIO_RESUMEN_XPATH = "//span[normalize-space()='Total Premio']/following::b[1]";
    public static final String FORMA_PAGO_SELECT_XPATH = "//input[@id='payment-method-form_paymentMethod']/ancestor::div[contains(@class,'ant-select')][1]";
    public static final String FORMA_PAGO_TABLE_HEADER_XPATH = "//th[normalize-space()='Forma de Pago']";
    public static final String MONTO_EXACTO_TABLE_HEADER_XPATH = "//th[contains(normalize-space(),'Monto Exacto')]";
    public static final String BANCO_TABLE_HEADER_XPATH = "//th[normalize-space()='Banco']";
    public static final String FECHA_TRANSFERENCIA_TABLE_HEADER_XPATH = "//th[normalize-space()='Fecha de Transferencia']";
    public static final String COMPROBANTE_PAGO_TABLE_HEADER_XPATH = "//th[normalize-space()='Comprobante de Pago']";
    public static final String TOTAL_A_PAGAR_LABEL_XPATH = "//span[normalize-space()='Total a Pagar']";
    public static final String SUMA_VALORES_LABEL_XPATH = "//span[normalize-space()='Suma de Valores']";
    public static final String SALDO_A_CUBRIR_LABEL_XPATH = "//span[normalize-space()='Saldo a Cubrir']";
    public static final String SALDO_A_CUBRIR_CERO_XPATH = "//span[normalize-space()='Saldo a Cubrir']/following::b[normalize-space()='$ 0,00' or normalize-space()='$  0,00'][1]";
    public static final String MONTO_EXACTO_INPUT_XPATH = "//label[contains(normalize-space(),'Monto Exacto')]/following::input[1]";
    public static final String BANCO_SELECT_XPATH = "//input[@id='payment-method-form_bank']/ancestor::div[contains(@class,'ant-select')][1]";
    public static final String FECHA_TRANSFERENCIA_INPUT_XPATH = "//label[contains(normalize-space(),'Fecha de Transferencia')]/following::input[1]";
    public static final String COMPROBANTE_UPLOAD_BUTTON_XPATH = "//div[@id='payment-method-form_proofOfPayment']//button[.//span[normalize-space()='Subir']]";
    public static final String COMPROBANTE_FILE_INPUT_XPATH = "//div[contains(@class,'ant-modal-content') and .//*[normalize-space()='Carga de Comprobantes']]//input[@type='file']";
    public static final String MODAL_CONFIRMAR_BUTTON_XPATH = "//div[contains(@class,'ant-modal-content') and .//*[normalize-space()='Carga de Comprobantes']]//button[.//span[normalize-space()='Confirmar']]";
    public static final String FORMA_PAGO_AGREGADA_XPATH = "//tbody//td[normalize-space()='%s']";
    public static final String BANCO_AGREGADO_XPATH = "//tbody//td[contains(normalize-space(),'%s')]";
    public static final String AGREGAR_BUTTON_XPATH = "//button[.//span[normalize-space()='Agregar']]";
    public static final String CONFIRMAR_PAGO_BUTTON_XPATH = "//button[normalize-space()='Confirmar el pago']";
    public static final String PRELIQUIDACION_ENVIADA_XPATH = "//h3[contains(normalize-space(),'La preliquidaci') and contains(normalize-space(),'ha sido enviada con') and contains(normalize-space(),'xito')]";
    public static final String GENERAR_PDF_BUTTON_XPATH = "//button[.//span[normalize-space()='Generar PDF']]";
    public static final String ACEPTAR_BUTTON_XPATH = "//button[.//span[normalize-space()='Aceptar']]";
    public static final String PRELIQUIDACIONES_GUARDADAS_ENVIADAS_TITULO_XPATH = "//h3[contains(normalize-space(),'Preliquidaciones Enviadas y Guardadas')]";
    public static final String PRELIQUIDACIONES_TAB_XPATH = "//div[@role='tab' and normalize-space()='%s']";
    public static final String PRELIQUIDACIONES_TAB_ACTIVA_XPATH = "//div[@role='tab' and @aria-selected='true' and normalize-space()='%s']";
    public static final String PRELIQUIDACIONES_PANEL_ACTIVO_XPATH = "//div[@role='tabpanel' and contains(@class,'ant-tabs-tabpane-active')]";
    public static final String PRELIQUIDACIONES_NUMERO_INPUT_XPATH = "//div[@role='tabpanel' and contains(@class,'ant-tabs-tabpane-active')]//input[@id='preliquidationNumber']";
    public static final String PRELIQUIDACIONES_FECHA_INICIAL_INPUT_XPATH = "//div[@role='tabpanel' and contains(@class,'ant-tabs-tabpane-active')]//input[@id='preliquidationDate' and @placeholder='Fecha inicial']";
    public static final String PRELIQUIDACIONES_FECHA_FINAL_INPUT_XPATH = "//div[@role='tabpanel' and contains(@class,'ant-tabs-tabpane-active')]//input[@date-range='end' and @placeholder='Fecha final']";
    public static final String PRELIQUIDACIONES_FILTRAR_BUTTON_XPATH = "//div[@role='tabpanel' and contains(@class,'ant-tabs-tabpane-active')]//button[.//span[normalize-space()='Filtrar']]";
    public static final String PRELIQUIDACIONES_BORRAR_FILTROS_BUTTON_XPATH = "//div[@role='tabpanel' and contains(@class,'ant-tabs-tabpane-active')]//button[.//span[normalize-space()='Borrar Filtros']]";
    public static final String PRELIQUIDACIONES_TABLE_XPATH = "//div[@role='tabpanel' and contains(@class,'ant-tabs-tabpane-active')]//table";
    public static final String PRELIQUIDACIONES_TABLE_HEADER_XPATH = "//div[@role='tabpanel' and contains(@class,'ant-tabs-tabpane-active')]//thead//th[normalize-space()='%s']";
    public static final String PRELIQUIDACIONES_FIRST_ROW_XPATH = "(//div[@role='tabpanel' and contains(@class,'ant-tabs-tabpane-active')]//tbody//tr[contains(@class,'ant-table-row')])[1]";
    public static final String PRELIQUIDACIONES_FIRST_ROW_NUMBER_XPATH = "(//div[@role='tabpanel' and contains(@class,'ant-tabs-tabpane-active')]//tbody//tr[contains(@class,'ant-table-row')])[1]/td[1]";
    public static final String PRELIQUIDACIONES_ROW_BY_NUMBER_XPATH = "//div[@role='tabpanel' and contains(@class,'ant-tabs-tabpane-active')]//tbody//tr[contains(@class,'ant-table-row')][td[1][normalize-space()='%s']]";
    public static final String PRELIQUIDACIONES_PAGINATION_TOTAL_XPATH = "//div[@role='tabpanel' and contains(@class,'ant-tabs-tabpane-active')]//li[contains(@class,'ant-pagination-total-text') and contains(normalize-space(),'preliquidaciones')]";
    public static final String PRELIQUIDACIONES_PAGE_SIZE_XPATH = "(//div[@role='tabpanel' and contains(@class,'ant-tabs-tabpane-active')]//*[contains(normalize-space(),'10 / p')])[1]";
    public static final String PRELIQUIDACIONES_ACCION_EDIT_XPATH = "(//div[@role='tabpanel' and contains(@class,'ant-tabs-tabpane-active')]//tbody//tr[contains(@class,'ant-table-row')]//span[@aria-label='edit'])[1]";
    public static final String PRELIQUIDACIONES_ACCION_DELETE_XPATH = "(//div[@role='tabpanel' and contains(@class,'ant-tabs-tabpane-active')]//tbody//tr[contains(@class,'ant-table-row')]//span[@aria-label='delete'])[1]";
    public static final String PRELIQUIDACIONES_ACCION_DOWNLOAD_XPATH = "(//div[@role='tabpanel' and contains(@class,'ant-tabs-tabpane-active')]//tbody//tr[contains(@class,'ant-table-row')]//span[@aria-label='download'])[1]";
}
